recommendVideo({
    'posterImgUrl':{
        'route':{
            'url0':'././img/01.jpg',
            'url1':'././img/02.jpg',
            'url2':'././img/03.jpg',
            'url3':'././img/04.jpg',
            'url4':'././img/05.jpg',
            'url5':'././img/06.jpg',
            'url6':'././img/07.jpg',
            'url7':'././img/08.jpg',
            'url8':'././img/09.jpg'
        },
        'iconUrl':'././img/redu.jpg',
        'videoTitle':{
            'title0':'React主要用5456456于构建UI，很多人认为 React 是 MVC 中的 V（视图）。',
            'title1':'哥我随手一来就是标准的十五个字',
            'title2':'有没有打农药的，保证带你上青铜，仅限妹子~~~',
            'title3':'大漠孤烟直，长河落日圆',
            'title4':'转朱阁，低绮户，照无眠，不应有恨，何事长向别时圆！',
            'title5':'村里有个姑娘叫小芳，长得美丽又善良~~·',
            'title6':'向前！向前！向前！我们的队伍像太阳！',
            'title7':'落霞与孤鹜齐飞，秋水共长天一色！',
            'title8':'鞋垫咯，卖鞋垫咯，不贵不要钱，快来买啊！·'

        },
        'playVolume':{
            'volume0':'2148',
            'volume1':'8466',
            'volume2':'2345',
            'volume3':'1044',
            'volume4':'854',
            'volume5':'9787',
            'volume6':'1546',
            'volume7':'8678',
            'volume8':'7534',
        }
    }
});